config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'cocktails#index'
  #COCKTAILS
  get 'cocktails', to: 'cocktails#index', as: 'cocktails'

  get 'cocktails/new', to: 'cocktails#new', as: 'new_cocktail'
  post 'cocktails', to: 'cocktails#create'

  get 'cocktails/:id', to: 'cocktails#show', as: 'cocktail'

  delete 'cocktails/:id',to: 'cocktails#destroy', as: 'destroy_cocktail'

  #DOSES
  resources :cocktails do
    resources :doses, only: [ :new, :create, :destroy ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, :uniqueness => true
  validates :name, :presence => true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates_presence_of :ingredient
  validates_presence_of :cocktail
  validates_presence_of :description

  validates_uniqueness_of :cocktail, :scope => [:ingredient]

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, :presence => true
  validates :name, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy

    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
    # @cocktail = Cocktail.new
    # @ingredient = Ingredient.new
  end

  def create
    id_ingredient = params["dose"]["ingredient_id"].to_i
    @dose = Dose.new(dose_params)
    @dose.ingredient = Ingredient.find(id_ingredient)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :cocktail_id, :quantity, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="home-banner">
  <h1>Welcome to Mr. Cocktails</h1>
  <p>Discover our library of craft mixes</p>
  <%= link_to 'Build a Cocktail', new_cocktail_path, :class => "btn btn-primary btn-lg"%>
</div>

<% @cocktails.each do |cocktail| %>
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://picsum.photos/200/300/?random');">
<!--   <div class="card-category">Top Drink</div> -->
  <div class="card-description">
    <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
    <p>Delicious & flavorful</p>
  </div>
  <a class="card-link" href="<%= cocktail_path(cocktail) %>" ></a>
</div>
<% end %>

app/views/cocktails/new.html.erb
<h1>Create a New Cocktail</h1>



<%= simple_form_for @cocktail do |f| %>
<% if @cocktail.errors.any? %>
<div class="errors-container">
  <ul>
    <% @cocktail.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.input :name %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.button :submit, :class => 'btn btn-primary' %>
<% end %>
<%= link_to "Take Me Back Home", cocktails_path, :class => 'btn btn-warning' %>

<!-- <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
</form>
-->

app/views/cocktails/show.html.erb
<div class="home-banner">
<h1><%= @cocktail.name %></h1>
</div>

<%= cl_image_tag @cocktail.photo, width: 200 %>


<% @cocktail.doses.each do |dose| %>

<h3>Ingredient: <%= dose.ingredient.name %>, Description: <%= dose.description %>, Quantity: <%= dose.quantity %> </h3>

<% end %>

<%= link_to "Take Me Back Home", cocktails_path, :class => 'btn btn-warning' %>
<%= link_to 'Add New Dose', new_cocktail_dose_path(@cocktail), :class => 'btn btn-primary' %>
<%= link_to 'Delete this Cocktail', destroy_cocktail_path(@cocktail), method: :delete, :class => 'btn btn-danger' %>

app/views/doses/new.html.erb
<h1>Create a New Dose</h1>

<%= simple_form_for ([@cocktail, @dose]) do |f| %>
<% if @dose.errors.any? %>
<div class="errors-container">
  <ul>
    <% @dose.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.association :ingredient %>
<%= f.input :quantity %>
<%= f.input :description %>
<%= f.button :submit, :class => 'btn btn-primary' %>
<% end %>

<%= link_to "Back to cocktail", cocktail_path(@cocktail), :class => 'btn btn-warning'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>



  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
</html>